version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: programwithgio-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./public:/var/www/public
      - ./app:/var/www/app

  nginx:
    image: nginx:1.19-alpine
    container_name: programwithgio-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/public
      - ./app:/var/www/app
      - ./nginx:/etc/nginx/conf.d
